### ISSUE TITLE
k8s + Cert manager 证书自动签发

### ISSUE THREAD

**Issue by HuihuangZhang** [HuihuangZhang/learning-note#2]
# 1. 背景

使用 lets encrypt 来签发 https 证书，lets encrypt 每次签发的证书有效期为 3 个月，可以在证书过期前 30 天内刷新证书。
域名使用 aliyun 的域名和 dns 解析。

k8s 的版本是 1.29.5
使用 ingress-nginx 来做 ingress 管理，ingress-nginx 版本是 1.10。

# 2. K8S + cert manager

适用场景：在 k8s 集群内部署 https 服务，可以使用 cert-manager 自动签发和续约证书。

## 2.1. 安装

> 参考：[^1] [^2]

```
helm repo add jetstack https://charts.jetstack.io
helm repo update
  
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.18.0 \
  --set crds.enabled=true \
  --set prometheus.enabled=false \
  --set webhook.hostNetwork=true \
  --set webhook.securePort=10260 \
  --set startupapicheck.timeout=5m \
  --set http_proxy=xxx \
  --set https_proxy=xxx \
  --set no_proxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
```

需要注意，
- 1.18 版本的 cert-manager 安装不需要额外手动安装 crd，只需要在 helm chart 安装时加上 `--set crds.enabled=true` ；
- `http_proxy` 和 `https_proxy` 是为了国内下载镜像和访问 letsenctypt 获取证书时加速使用，如果不需要，可以去掉这两个参数；
- `webhook.hostNetwork` 和 `webhook.securePort` 参数是因为 webhook 的 context deadline exceeded 问题 [^2]；

卸载：`helm uninstall cert-manager --namespace cert-manager`

## 2.2. 集成阿里云

> 参考：[^3]

集成 阿里云 的 webhook，用来自动签发在 阿里云 上管理的域名的证书。
在这里举例签发的域名是 `mos-dev.moleculemind.tech`

> Clusterissuer 是全局的，每个 namespace 都可以访问；
> Certificate 是绑定 namespace 的；

安装：
1. 安装基本的 webhook 资源

```
kubectl apply -f https://raw.githubusercontent.com/pragkent/alidns-webhook/master/deploy/bundle.yaml
```

需要将其中的 groupname 都改成自己命名的字符串（使用配置里面的 `acme.yourcompany.com` 也没问题，只是语义不清晰）。在后续的 ClusterIssuer 配置中还需要被用到。

例如我改成 `aliyun.webhook` 的配置文件： [alidns-webhook-bundle.yaml](https://github.com/HuihuangZhang/learning-note/blob/master/notes/k8s_cert_manager/alidns-webhook-bundle.yaml)

2. 申请阿里云的 access key 和 secret key。在阿里云的控制台就可以申请，需要有权限。生成 k8s secret:

```
kubectl create secret generic alidns-secret \
  --from-literal=access-key=<ACCESS_KEY> \
  --from-literal=secret-key=<SECRET_KEY> \
  --namespace cert-manager
```

3. 安装 `ClusterIssuer`

```
# cluster-issuer-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    email: <YOUR_EMAIL>
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-dns
    solvers:
    - dns01:
        webhook:
          groupName: alidns.webhook
          solverName: alidns
          config:
            region: ""
            accessKeySecretRef:
              name: alidns-secret
              key: access-key
            secretKeySecretRef:
              name: alidns-secret
              key: secret-key
```

```
# cluster-issuer-prod.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    email: <YOUR_EMAIL>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    solvers:
    - dns01:
        webhook:
          groupName: alidns.webhook
          solverName: alidns
          config:
            region: ""
            accessKeySecretRef:
              name: alidns-secret
              key: access-key
            secretKeySecretRef:
              name: alidns-secret
              key: secret-key
```

  执行 `kubectl apply -f xxx.yaml` 安装。

4. 安装 `Certificate` 资源

```
# certificate-staging.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: moleculemind-tech-staging-tls
spec:
  secretName: moleculemind-tech-staging-tls
  commonName: moleculemind.tech
  dnsNames:
  - moleculemind.tech
  - "*.moleculemind.tech"
  issuerRef:
    name: letsencrypt-staging-dns
    kind: ClusterIssuer
```

```
# certificate-prod.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: moleculemind-tech-prod-tls
spec:
  secretName: moleculemind-tech-prod-tls
  commonName: moleculemind.tech
  dnsNames:
  - moleculemind.tech
  - "*.moleculemind.tech"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
```

  注意：`issuerRef.name` 需要和上面的 `ClusterIssuer.metadata.name` 保持一致。
  配置文件中签发的是泛域名证书。

5. 执行命令查看证书签发情况

```
kubectl get clusterissuer
kubectl get certificate -n mos

kubectl -n mos describe cert moleculemind-tech-staging-tls
kubectl -n mos describe cert moleculemind-tech-prod-tls
```

  等待其到 READY = True，会生成对应的 tls secret，通过 `kubectl get secret -n mos` 进行查看。

```
$ kubectl get secret -n mos

NAME                                          TYPE                             DATA   AGE
moleculemind-tech-prod-tls                    kubernetes.io/tls                2      4d23h
moleculemind-tech-staging-tls                 kubernetes.io/tls                2      5d
```

6. 在 ingress 中上使用

```
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mos-gateway-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /v1/$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
spec:
  ingressClassName: nginx
  tls: 
    - hosts:
        - mos-dev.moleculemind.tech
      secretName: moleculemind-tech-prod-tls
  rules:
    - host: mos-dev.moleculemind.tech
      http:
        paths:
          - path: /ping
            pathType: ImplementationSpecific
            backend:
              service:
                name: mos-gateway-api
                port:
                  number: 8888
```

  需要在使用 cert-manager 签发证书的地方加上 `metadata.annotations` 字段 `cert-manager.io/cluster-issuer`，先尝试使用 staging 环境的 ClusterIssuer 和 secret，没问题后再切换成 prod 环境的资源。

需要安装 staging 和 prod 环境 letsencrypt server 的 ClusterIssuer 和 Certificate 资源。
> 关于 staging 环境和 prod 环境参考：https://letsencrypt.org/zh-cn/docs/staging-environment/

# 3. certbot + certbot-dns-aliyun[^4]

适用场景：普通的服务场景，例如 nginx 安装在 linux 服务器上做 tls 证书认证，并做方向代理路由给下游的服务（ip:port）。

举例情况：机器 OS 为 debian12，在机器上使用 docker 安装 nginx 进行反向代理。证书通过 `-v` 的形式挂载到 nginx 容器中，并在 `nginx.conf` 中配置证书。

1. 安装 certbot: `sudo apt-get install certbot`
2. 安装 certbot-dns-aliyun [^4]，使用手动安装的方式

```
git clone https://github.com/tengattack/certbot-dns-aliyun
cd certbot-dns-aliyun
sudo python setup.py install
```

3. 登录获取 [aliyun](https://ram.console.aliyun.com/) 的 access-key 和 secret-key。需要确保账号有 `AliyunDNSFullAccess` 的权限；
4. 新建 `/etc/certbot/alidns-credentials.ini`，将以下信息写入文件中：

```
dns_aliyun_access_key = <access-key>
dns_aliyun_access_key_secret = <secret-key>
```

5. 运行以下命令，获取证书：

```
certbot certonly \
    --authenticator=dns-aliyun \
    --dns-aliyun-credentials='/etc/certbot/alidns-credentials.ini' \
    -d "*.moleculemind.tech,moleculemind.tech"
```

正常情况下会输出类似以下信息：

```
Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/moleculemind.tech/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/moleculemind.tech/privkey.pem
```

6. 后续执行 `certbot renew` 来续约证书。续约证书后，可以执行 `openssl x509 -in /etc/letsencrypt/live/moleculemind.tech/fullchain.pem -noout -dates` 查看证书有效期。每次续约证书后，需要重启 nginx 以部署新证书。

# 参考

[^1]: Cert-manager helm 官方教程： [cert-manager helm](https://cert-manager.io/docs/installation/helm/)
[^2]: github issue: [Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded](https://github.com/cert-manager/cert-manager/issues/5189#issuecomment-1316613068)
[^3]: github cert-manager + aliyun demo: [k8s-cret-manager-aliyun-webhook-demo](https://github.com/PowerDos/k8s-cret-manager-aliyun-webhook-demo?tab=readme-ov-file)
[^4]: https://github.com/tengattack/certbot-dns-aliyun?tab=readme-ov-file
